
name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.teamcity/**'
      - 'README.adoc'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    name: Build - Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build and run tests
        run: ./gradlew --show-version -s build
