
name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.teamcity/**'
      - 'README.adoc'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11 ]
    name: Build - Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --show-version -s build
